name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic version'
        required: true
        type: string
  push:
    tags:
    - 'v[0-9].[0-9].[0-9]'

env:
  # Use docker.io for Docker Hub if empty
  REPOSITORY: to-do-app-repo #ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ inputs.tag || (github.event_name == 'push' && github.ref_name)}}
  ASSUMABLE_ROLE: ${{ secrets.assumable_role }}
  AWS_REGION: eu-central-1
  CLUSTER_NAME: cluster-andjela

jobs:
  build:
    #if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Checkout repo
      #   uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{env.ASSUMABLE_ROLE}}
          aws-region: ${{env.AWS_REGION}} 
          mask-aws-account-id: 'true'


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry}}/${{ env.REPOSITORY }}:docker-${{env.IMAGE_TAG}}
      
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{env.AWS_REGION}}

      - name: Deploy to EKS
        run: helm upgrade todo-app --set "container.tag"="${{env.IMAGE_TAG}}" --namespace vegait-training oci://${{ steps.login-ecr.outputs.registry}}/${{env.REPOSITORY}}
